export default ({
	GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
	SOCKET_MESSAGE_REQUEST: 'SOCKET_MESSAGE_REQUEST',
	SOCKET_PENDING: 'SOCKET_PENDING',
	SOCKET_CONNECTED: 'SOCKET_CONNECTED',
	SOCKET_CONNECTION_FAILURE: 'SOCKET_CONNECTION_FAILURE'
});