export default ({
	GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
	FETCH_MESSAGE_REQUEST: 'FETCH_MESSAGE_REQUEST',
	FETCH_MESSAGE_FAILURE: 'FETCH_MESSAGE_FAILURE',
	SOCKET_PENDING: 'SOCKET_PENDING',
	SOCKET_CONNECTED: 'SOCKET_CONNECTED',
	SOCKET_CONNECTION_FAILURE: 'SOCKET_CONNECTION_FAILURE'
});